@isTest(seealldata=true)
public class LightningtestclassforCase {
   /* static testMethod void casetestMethod() 
    {
        case oCase = [SELECT Id  FROM Case where status='New Case' limit 1 ];
    
         list<Case> result = closecaselightning.getcase(oCase.Id);
    
         list<case> result1 = closecaselightning.getquotefields(ocase.id);
        
       //  list<Con_Req_Group__c> result2 = CreateConreqfromcaseController.createconreq(ocase.id);

    } */
    
        
}